### ISSUE TITLE
Hex map suggestions

### ISSUE THREAD

**Issue by tomwhite** [odileeds/covid-19#1]
Hex map
* Wales LA (local authority) -> HB (health board) conversion is here: https://github.com/tomwhite/covid-19-uk-data/blob/gh-pages/covid-19-daily-cases-uk-by-area.html#L89. So it should be possible to go through and convert older dates when Wales reported LAs and convert them to HB. Then on the map have multiple hexagons correspond to one HB (like you have done for Cornwall and Isles of Scilly in England).
* There are case numbers for NI now (on weekdays at least), so you should be able to add those fairly easily.
* I'm not sure about the mapping for Scottish LA -> HB.
* I didn't realise you had to click to get the info - it would be nice to add the value at least to the tooltip.
* The hex map could do with a key to show what the colours mean.

Confirmed cases
* It would be good to have a lookup/dropdown so you can search for a particular area.

**Comment by slowe** [comment]
@tomwhite  Adding Wales, NI and Scotland (using https://github.com/watty62/Scot_covid19 / https://www.dropbox.com/s/s2en5rf72zpdbag/Health%20Board%20to%20LA%20Look%20Up.xlsx?dl=0) and adding a search for the Confirmed Cases plot are on my todo list already :)

The other points are good ideas so I'll add them too.

**Comment by slowe** [comment]
@tomwhite Wales, Scotland, and Northern Ireland are now added using populations and lookups from that DropBox link. Thanks!

**Comment by tomwhite** [comment]
Looks great - thanks for fixing it!

BTW https://github.com/tomwhite/covid-19-uk-data/issues/33 might be relevant to you.

**Comment by slowe** [comment]
Now added the numbers to the hover text on the hex map.
