### ISSUE TITLE
Hexmap population

### ISSUE THREAD

**Issue by aebaldwin** [odileeds/covid-19#2]
In the hexmap, the displayed population is about half of what I'd expect it to be (eg Newcastle listed as 153,228 when I know the population is around 300,000), I am guessing it's just picking up M or F rather than both (or I'm being dense)

**Comment by slowe** [comment]
@aebaldwin Looks like you are right. I'll update them.

**Comment by slowe** [comment]
Done. [Test it out](https://odileeds.github.io/covid-19/LocalAuthorities/?hextype=COVID-19-percapita)
